spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  session:
    jdbc:
      initialize-schema: always
      platform: postgresql

logging.level:
  root: ERROR
  org.springframework.jdbc: TRACE
